version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: "America/Santiago"
    labels:
      - dependencies
      - npm
    commit-message:
      prefix: deps
      include: scope
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types: ["minor", "patch"]
      dev-dependencies:
        dependency-type: "development"
        update-types: ["minor", "patch"]
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: "America/Santiago"
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: deps
      include: scope

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: "America/Santiago"
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: deps
      include: scope
